# Generated by Django 3.1.6 on 2021-02-04 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_auto_20210203_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingspot',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='parkingspot',
            old_name='lon',
            new_name='longitude',
        ),
    ]
