# Generated by Django 3.1.6 on 2021-02-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_auto_20210204_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_transaction_id',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='refund_transaction_id',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='refund_status',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
