# Generated by Django 3.1.6 on 2021-02-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_auto_20210204_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='name',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='parkingspot',
            unique_together={('name', 'latitude', 'longitude')},
        ),
    ]
