# Generated by Django 3.1.6 on 2021-02-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('last_name', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=250, null=True)),
                ('phone', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(blank=True, max_length=1024, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modification_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
