# Generated by Django 3.1.6 on 2021-02-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='Mobile',
            field=models.BigIntegerField(),
        ),
    ]
